# Generated by Django 2.2.10 on 2021-11-24 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_auto_20211124_1747'),
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='adhoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution', to='ops.AdHoc'),
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution', to='ops.Task'),
        ),
        migrations.AddField(
            model_name='adhoc',
            name='hosts',
            field=models.ManyToManyField(to='assets.Asset', verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='adhoc',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc', to='ops.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'org_id')},
        ),
    ]
