# Generated by Django 2.2.10 on 2021-11-24 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_auto_20211124_1747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_auto_20211124_1747'),
        ('users', '0001_initial'),
        ('perms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteapppermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='remoteapppermission',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='databaseapppermission',
            name='database_apps',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='applications.DatabaseApp', verbose_name='DatabaseApp'),
        ),
        migrations.AddField(
            model_name='databaseapppermission',
            name='system_users',
            field=models.ManyToManyField(related_name='granted_by_database_app_permissions', to='assets.SystemUser', verbose_name='System user'),
        ),
        migrations.AddField(
            model_name='databaseapppermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='databaseapppermission',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.Asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.Node', verbose_name='Nodes'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='system_users',
            field=models.ManyToManyField(related_name='granted_by_permissions', to='assets.SystemUser', verbose_name='System user'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='remoteapppermission',
            unique_together={('org_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='databaseapppermission',
            unique_together={('org_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='assetpermission',
            unique_together={('org_id', 'name')},
        ),
    ]
