# Generated by Django 2.2.10 on 2021-12-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskinfo',
            name='autoanspshot',
            field=models.CharField(blank=True, choices=[('True', '启用'), ('False', '未启用')], max_length=64, null=True, verbose_name='Snapshot policy function'),
        ),
        migrations.AlterField(
            model_name='diskinfo',
            name='delwith',
            field=models.CharField(choices=[('False', '保留不释放'), ('True', '随实例释放')], default='false', max_length=64, verbose_name='Release method'),
        ),
        migrations.AlterField(
            model_name='diskinfo',
            name='snapshot',
            field=models.CharField(blank=True, choices=[('True', '已设置'), ('False', '未设置')], max_length=64, null=True, verbose_name='Automatic snapshot strategy'),
        ),
    ]
