# Generated by Django 2.2.10 on 2021-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0051_auto_20211106_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetexpansion',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='balanced',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='diskinfo',
            name='update_time',
        ),
        migrations.AddField(
            model_name='assetexpansion',
            name='update_data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated'),
        ),
        migrations.AddField(
            model_name='balanced',
            name='update_data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated'),
        ),
        migrations.AddField(
            model_name='diskinfo',
            name='update_data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='assetexpansion',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Hostname'),
        ),
    ]
