# Generated by Django 2.2.10 on 2021-12-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteapp',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset', verbose_name='Asset'),
        ),
        migrations.AlterUniqueTogether(
            name='databaseapp',
            unique_together={('org_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='remoteapp',
            unique_together={('org_id', 'name')},
        ),
    ]
