# Generated by Django 2.2.10 on 2021-10-19 07:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudInfor',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('value', models.CharField(blank=True, max_length=128, null=True, verbose_name='Value')),
                ('key', models.CharField(blank=True, max_length=128, null=True, verbose_name='key')),
                ('secret', models.CharField(blank=True, max_length=128, null=True, verbose_name='Secret')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=128, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'CloudInfor',
                'ordering': ['name'],
                'unique_together': {('org_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Name')),
                ('env', models.CharField(choices=[('dev', 'dev'), ('test', 'test'), ('uat', 'uat'), ('pre', 'pre'), ('gra', 'gra'), ('prd', 'prd')], default='', max_length=32, verbose_name='Env')),
                ('address', models.CharField(blank=True, db_index=True, max_length=512, null=True, verbose_name='Address')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Password')),
                ('kibana', models.URLField(blank=True, max_length=512, null=True, verbose_name='Kibana addr')),
                ('kafka', models.URLField(blank=True, max_length=512, null=True, verbose_name='Kafka addr')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('labels', models.CharField(blank=True, max_length=32, null=True, verbose_name='Labels')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudinfor', to='elastics.CloudInfor', verbose_name='Cloud')),
            ],
            options={
                'verbose_name': 'MetaInfo',
                'ordering': ['name'],
            },
        ),
    ]
