# Generated by Django 2.2.10 on 2021-12-25 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malfunction',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=128, verbose_name='Created by')),
                ('metainfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elastics.MetaInfo', verbose_name='Metainfo')),
            ],
            options={
                'verbose_name': 'Malfunction',
                'ordering': ['-date_created'],
            },
        ),
    ]
