# Generated by Django 2.2.10 on 2021-11-04 08:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsNode',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('disktotal', models.BigIntegerField(verbose_name='Disk total')),
                ('diskused', models.BigIntegerField(verbose_name='Disk used')),
                ('diskavail', models.BigIntegerField(verbose_name='Disk avail')),
                ('ramcurrent', models.BigIntegerField(verbose_name='Used total memory')),
                ('rammax', models.BigIntegerField(verbose_name='Total memory')),
                ('noderole', models.CharField(db_index=True, max_length=64, verbose_name='Node roles')),
                ('pid', models.IntegerField(verbose_name='Process id')),
                ('port', models.IntegerField(verbose_name='Transmission port')),
                ('http_address', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Http monitoring')),
                ('version', models.CharField(max_length=64, verbose_name='Version')),
                ('jdk', models.CharField(db_index=True, max_length=64, verbose_name='Jdk version')),
                ('uptime', models.CharField(db_index=True, max_length=64, verbose_name='Running uptime')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('metainfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.MetaInfo', verbose_name='Metainfo')),
            ],
            options={
                'verbose_name': 'EsNode',
                'ordering': ['ip'],
            },
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
