# Generated by Django 2.2.10 on 2021-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterremote',
            options={'ordering': ['-date_updated'], 'verbose_name': 'ClusterRemote'},
        ),
        migrations.AlterModelOptions(
            name='clustersetting',
            options={'ordering': ['-date_updated'], 'verbose_name': 'ClusterSetting'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Index'},
        ),
        migrations.AlterModelOptions(
            name='indiceshard',
            options={'ordering': ['-date_updated'], 'verbose_name': 'IndiceShard'},
        ),
        migrations.AddField(
            model_name='metainfo',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Remote'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='scbcl',
            field=models.BooleanField(default=False, verbose_name='Sync across clusters'),
        ),
        migrations.AlterField(
            model_name='indiceshard',
            name='sto',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Shard store size(GB)'),
        ),
    ]
