# Generated by Django 2.2.10 on 2021-10-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinfor',
            name='key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Key'),
        ),
    ]
