# Generated by Django 2.2.10 on 2021-12-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0002_malfunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esnode',
            name='diskavail',
            field=models.BigIntegerField(verbose_name='Avail Disk'),
        ),
        migrations.AlterField(
            model_name='esnode',
            name='disktotal',
            field=models.BigIntegerField(verbose_name='Total disk'),
        ),
        migrations.AlterField(
            model_name='esnode',
            name='diskused',
            field=models.BigIntegerField(verbose_name='Used disk'),
        ),
    ]
