# Generated by Django 2.2.10 on 2021-12-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0002_auto_20211206_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metainfo',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Remote cluster'),
        ),
    ]
