# Generated by Django 2.2.10 on 2021-10-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0002_auto_20211020_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='metainfo',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Created by'),
        ),
    ]
