# Generated by Django 2.2.10 on 2021-11-08 10:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0002_auto_20211104_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustersetting',
            name='def_clus',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Default cluster parameters'),
        ),
        migrations.AlterField(
            model_name='clustersetting',
            name='def_xpack',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Security'),
        ),
        migrations.AlterField(
            model_name='clustersetting',
            name='persis',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Permanent parameters'),
        ),
        migrations.AlterField(
            model_name='clustersetting',
            name='tran',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Temporary parameters'),
        ),
    ]
