# Generated by Django 2.2.10 on 2021-12-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0003_auto_20211226_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esnode',
            name='diskavail',
            field=models.BigIntegerField(verbose_name='Avail disk'),
        ),
    ]
