# Generated by Django 2.2.10 on 2021-11-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0003_auto_20211108_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metainfo',
            old_name='index',
            new_name='indexes',
        ),
    ]
