# Generated by Django 2.2.10 on 2021-12-07 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0003_auto_20211207_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakerConfig',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fielddata_over', models.FloatField(blank=True, null=True, verbose_name='Fielddata overhead')),
                ('request_over', models.CharField(blank=True, max_length=16, null=True, verbose_name='Request overhead')),
                ('total_limit', models.CharField(blank=True, max_length=16, null=True, verbose_name='Total limit')),
                ('request_limit', models.CharField(blank=True, max_length=16, null=True, verbose_name='Request limit')),
                ('fielddata_limit', models.CharField(blank=True, max_length=16, null=True, verbose_name='Fielddata limit')),
                ('inflight_req', models.FloatField(blank=True, null=True, verbose_name='Inflight_requests overhead')),
                ('inflight_req_limit', models.CharField(blank=True, max_length=16, null=True, verbose_name='Inflight_requests limit')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('created_by', models.CharField(blank=True, default='', max_length=128, verbose_name='Created by')),
                ('metainfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.MetaInfo', verbose_name='Metainfo')),
            ],
            options={
                'verbose_name': 'BreakerConfig',
            },
        ),
        migrations.CreateModel(
            name='RoutingConfig',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rebalance_enable', models.CharField(blank=True, max_length=16, null=True, verbose_name='Rebalance enable')),
                ('node_concurrent_recoveries', models.IntegerField(blank=True, null=True, verbose_name='Node concurrent recoveries')),
                ('disk_watermark_flood_stage', models.CharField(blank=True, max_length=16, null=True, verbose_name='Disk watermark flood stage')),
                ('node_initial_primaries_recoveries', models.IntegerField(blank=True, null=True, verbose_name='Node initial primaries recoveries')),
                ('allow_rebalance', models.CharField(blank=True, max_length=16, null=True, verbose_name='Allow rebalance')),
                ('cluster_concurrent_rebalance', models.IntegerField(blank=True, null=True, verbose_name='Cluster concurrent rebalance')),
                ('disk_watermark_low', models.CharField(blank=True, max_length=16, null=True, verbose_name='Disk watermark low')),
                ('disk_watermark_high', models.CharField(blank=True, max_length=16, null=True, verbose_name='Disk watermark high')),
                ('allocation_enable', models.CharField(blank=True, max_length=16, null=True, verbose_name='Allocation enable')),
                ('awareness_attributes', models.CharField(blank=True, max_length=16, null=True, verbose_name='Awareness attributes')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('created_by', models.CharField(blank=True, default='', max_length=128, verbose_name='Created by')),
                ('metainfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.MetaInfo', verbose_name='Metainfo')),
            ],
            options={
                'verbose_name': 'RoutingConfig',
            },
        ),
        migrations.CreateModel(
            name='BreakerConfigNum',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('breakerconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.BreakerConfig', verbose_name='BreakerConfig')),
                ('metainfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.MetaInfo', verbose_name='Metainfo')),
            ],
            options={
                'verbose_name': 'BreakerConfigNum',
            },
        ),
    ]
