# Generated by Django 2.2.10 on 2021-11-10 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0004_auto_20211110_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('uuid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Uuid')),
                ('pri', models.CharField(blank=True, max_length=256, null=True, verbose_name='Primary shard')),
                ('rep', models.IntegerField(blank=True, max_length=256, null=True, verbose_name='Replica Set')),
                ('dc', models.BigIntegerField(blank=True, max_length=256, null=True, verbose_name='Total docs')),
                ('ssize', models.BigIntegerField(blank=True, null=True, verbose_name='Store size')),
                ('pss', models.BigIntegerField(blank=True, null=True, verbose_name='Pri store size')),
                ('health', models.CharField(max_length=32, verbose_name='Health')),
                ('status', models.CharField(max_length=32, verbose_name='Status')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('metainfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.MetaInfo', verbose_name='Metainfo')),
            ],
            options={
                'verbose_name': 'Index',
                'ordering': ['name', 'date_updated'],
            },
        ),
    ]
