# Generated by Django 2.2.10 on 2021-12-08 07:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0004_breakerconfig_breakerconfignum_routingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingconfig',
            name='balance_index',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Balance index'),
        ),
        migrations.AddField(
            model_name='routingconfig',
            name='balance_shard',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Balance shard'),
        ),
        migrations.AddField(
            model_name='routingconfig',
            name='balance_threshold',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Balance threshold'),
        ),
        migrations.AddField(
            model_name='routingconfig',
            name='node_concurrent_outgoing_recoveries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Node concurrent outgoing recoveries'),
        ),
        migrations.CreateModel(
            name='RoutingConfigNum',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('metainfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.MetaInfo', verbose_name='Metainfo')),
                ('routingConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.BreakerConfig', verbose_name='RoutingConfig')),
            ],
            options={
                'verbose_name': 'RoutingConfigNum',
            },
        ),
    ]
