# Generated by Django 2.2.10 on 2021-11-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0005_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='dc',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Total docs'),
        ),
        migrations.AlterField(
            model_name='index',
            name='rep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Replica Set'),
        ),
    ]
