# Generated by Django 2.2.10 on 2021-11-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0006_auto_20211110_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='esnode',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
