# Generated by Django 2.2.10 on 2021-11-18 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0007_esnode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='NodeFs',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Data path')),
                ('mount', models.CharField(blank=True, max_length=512, null=True, verbose_name='Mount path')),
                ('filesystem', models.CharField(max_length=64, null=True, verbose_name='File system')),
                ('total', models.BigIntegerField(verbose_name='Total size')),
                ('free', models.BigIntegerField(verbose_name='Free size')),
                ('available', models.BigIntegerField(verbose_name='Available')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('esnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.EsNode', verbose_name='Esnode')),
            ],
            options={
                'verbose_name': 'NodeFs',
            },
        ),
        migrations.CreateModel(
            name='IndiceShard',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shardid', models.IntegerField(verbose_name='Shardid')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='State')),
                ('pri', models.CharField(blank=True, max_length=64, null=True, verbose_name='Primary shard')),
                ('relocating_node', models.CharField(blank=True, max_length=512, null=True, verbose_name='Relocating node')),
                ('docs', models.BigIntegerField(verbose_name='Docs')),
                ('store', models.IntegerField(verbose_name='Store')),
                ('recovery', models.IntegerField(verbose_name='Recovery')),
                ('shard_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='shard path')),
                ('data_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Data path')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('esnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.EsNode', verbose_name='Esnode')),
                ('indices', models.ManyToManyField(to='elastics.Index', verbose_name='Indices')),
            ],
            options={
                'verbose_name': 'IndiceShard',
                'ordering': ['date_updated'],
            },
        ),
        migrations.CreateModel(
            name='IndiceNode',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('refresh', models.IntegerField(verbose_name='Refresh')),
                ('flush', models.IntegerField(verbose_name='Flush')),
                ('recovery', models.IntegerField(verbose_name='Recovery')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('esnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.EsNode', verbose_name='Esnode')),
                ('indices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastics.Index', verbose_name='Index')),
            ],
            options={
                'verbose_name': 'IndiceNode',
            },
        ),
    ]
