# Generated by Django 2.2.10 on 2021-12-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0007_auto_20211208_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingconfig',
            name='allow_rebalance',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Allow rebalance'),
        ),
    ]
