# Generated by Django 2.2.10 on 2021-11-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastics', '0008_auto_20211118_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='esnode',
            name='uuid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Uuid'),
        ),
    ]
